version: '3.5'
services:
  go:
    build:
      context: .
    image: go_tw_stock
    container_name: go_tw_stock
    env_file: .env
    volumes: 
      - ./goTwStock:/go/goTwStock:rw
      - ./pkg:/go/pkg:rw
    tty: true
